# revision 33208
# category Package
# catalog-ctan /fonts/fira
# catalog-date 2014-03-28 17:26:17 +0100
# catalog-license ofl
# catalog-version undef
Name:		texlive-fira
Version:	20140328
Release:	1
Summary:	Fira fonts with LaTeX support
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/fonts/fira
License:	OFL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/fira.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/fira.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
This package provides LaTeX, pdfLaTeX, XeLaTeX and LuaLaTeX
support for the Fira Sans family of fonts (version 2.001),
designed by Erik Spiekermann and Ralph du Carrois of Carrois
Type Design. Fira Sans is available in four weights with
corresponding italics: light, regular, medium, and bold.

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_3p7daj.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_43cgqx.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_4ai6s3.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_5vo6v3.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_6stq6l.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_7dora6.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_7pa6nr.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_bbisrg.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_bcaxam.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_cexy2a.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_diwkq2.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_dzjeln.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_epfzfv.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_g5h2wm.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_gfyuxe.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_hv4ypj.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_iqn6bq.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_mrv5cv.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_o5eujx.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_psi4jm.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_rxzygj.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_sztozt.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_tbwpt7.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_tjdeuc.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_ur52lz.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_vrlpiq.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_x5cx63.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_y35fae.enc
%{_texmfdistdir}/fonts/enc/dvips/fira/fir_yjq6vf.enc
%{_texmfdistdir}/fonts/map/dvips/fira/fira.map
%{_texmfdistdir}/fonts/opentype/carrois/fira/FiraSansOT-Bold.otf
%{_texmfdistdir}/fonts/opentype/carrois/fira/FiraSansOT-BoldItalic.otf
%{_texmfdistdir}/fonts/opentype/carrois/fira/FiraSansOT-Light.otf
%{_texmfdistdir}/fonts/opentype/carrois/fira/FiraSansOT-LightItalic.otf
%{_texmfdistdir}/fonts/opentype/carrois/fira/FiraSansOT-Medium.otf
%{_texmfdistdir}/fonts/opentype/carrois/fira/FiraSansOT-MediumItalic.otf
%{_texmfdistdir}/fonts/opentype/carrois/fira/FiraSansOT-Regular.otf
%{_texmfdistdir}/fonts/opentype/carrois/fira/FiraSansOT-RegularItalic.otf
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Bold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-BoldItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-Italic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOT-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-Italic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTLight-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-Italic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/carrois/fira/FiraSansOTMedium-tosf-ts1.tfm
%{_texmfdistdir}/fonts/type1/carrois/fira/FiraSansOT-Bold.pfb
%{_texmfdistdir}/fonts/type1/carrois/fira/FiraSansOT-BoldItalic.pfb
%{_texmfdistdir}/fonts/type1/carrois/fira/FiraSansOT-Italic.pfb
%{_texmfdistdir}/fonts/type1/carrois/fira/FiraSansOT.pfb
%{_texmfdistdir}/fonts/type1/carrois/fira/FiraSansOTLight-Italic.pfb
%{_texmfdistdir}/fonts/type1/carrois/fira/FiraSansOTLight.pfb
%{_texmfdistdir}/fonts/type1/carrois/fira/FiraSansOTMedium-Italic.pfb
%{_texmfdistdir}/fonts/type1/carrois/fira/FiraSansOTMedium.pfb
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-lf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-sup-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Bold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-BoldItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-Italic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-lf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-osf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-sup-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOT-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-Italic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-lf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-osf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-sup-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTLight-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-Italic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-lf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-osf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-sup-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/carrois/fira/FiraSansOTMedium-tosf-ts1.vf
%{_texmfdistdir}/tex/latex/fira/FiraSans.sty
%{_texmfdistdir}/tex/latex/fira/LY1FiraSansOT-LF.fd
%{_texmfdistdir}/tex/latex/fira/LY1FiraSansOT-OsF.fd
%{_texmfdistdir}/tex/latex/fira/LY1FiraSansOT-Sup.fd
%{_texmfdistdir}/tex/latex/fira/LY1FiraSansOT-TLF.fd
%{_texmfdistdir}/tex/latex/fira/LY1FiraSansOT-TOsF.fd
%{_texmfdistdir}/tex/latex/fira/OT1FiraSansOT-LF.fd
%{_texmfdistdir}/tex/latex/fira/OT1FiraSansOT-OsF.fd
%{_texmfdistdir}/tex/latex/fira/OT1FiraSansOT-Sup.fd
%{_texmfdistdir}/tex/latex/fira/OT1FiraSansOT-TLF.fd
%{_texmfdistdir}/tex/latex/fira/OT1FiraSansOT-TOsF.fd
%{_texmfdistdir}/tex/latex/fira/T1FiraSansOT-LF.fd
%{_texmfdistdir}/tex/latex/fira/T1FiraSansOT-OsF.fd
%{_texmfdistdir}/tex/latex/fira/T1FiraSansOT-Sup.fd
%{_texmfdistdir}/tex/latex/fira/T1FiraSansOT-TLF.fd
%{_texmfdistdir}/tex/latex/fira/T1FiraSansOT-TOsF.fd
%{_texmfdistdir}/tex/latex/fira/TS1FiraSansOT-LF.fd
%{_texmfdistdir}/tex/latex/fira/TS1FiraSansOT-OsF.fd
%{_texmfdistdir}/tex/latex/fira/TS1FiraSansOT-TLF.fd
%{_texmfdistdir}/tex/latex/fira/TS1FiraSansOT-TOsF.fd
%doc %{_texmfdistdir}/doc/fonts/fira/Fira_Sans_font_specimen.png
%doc %{_texmfdistdir}/doc/fonts/fira/LICENSE
%doc %{_texmfdistdir}/doc/fonts/fira/README
%doc %{_texmfdistdir}/doc/fonts/fira/fira-samples.pdf
%doc %{_texmfdistdir}/doc/fonts/fira/fira-samples.tex

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar fonts tex doc %{buildroot}%{_texmfdistdir}
